server: 
  port: 9008
spring: 
  application:  
    name: ten-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.112.128:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.112.128
  redis:
    host: 192.168.112.128
jwt:
  config:
    key: gls111
    ttl: 360000
